### ISSUE TITLE
Enhancement: Add aliases to entries in search modal.

### ISSUE THREAD

**Issue by jmonroynieto** [o02c/obsidian-tab-navigator#13]
This has been a fantastic help in the few days I have used it. Thanks a lot.

One of the things that would make this plugin useful for me and add value to many people would be adding the aliases of the tabs to the search box (modal). The aliases help me understand better what topics each note has; the extra info would allow those of us who use aliases to reap the benefits of writing them. I envision the aliases as smaller font highlighted boxes right by the names with the highlight color as their background.

![Search_idea](https://github.com/o02c/obsidian-tab-navigator/assets/10119293/1dc39db2-1902-4d35-bb30-f623ccb53764)

I understand this might be a personal project but I'm not a JS dev so I can't contribute a PR to help out. I took a look at the code, and wondered whether, to start prototyping,  changing the [search model](https://github.com/o02c/obsidian-tab-navigator/blob/029cb97db1bb62df193fea3fb4c42c340bf3ee23/src/model/SearchModel.svelte#L51) by appending the aliases to the `titleorname` variable would be a good first step. I know that the obsidian API offers [getFileCache](https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFileCache) to access the frontmatter info quickly. I attempted the changes directly on the transpiled version installed on my vault but all I do is break it. I would very much appreciate it if you could look into it.

**Comment by o02c** [comment]
Thank you for your suggestion!

We've implemented the feature to include aliases in the search modal in version 0.3.1. Please note that the aliases are displayed next to the titles with @alias1 @alias2 ... (This setting can be toggled from the options menu.)

We hope this update helps. Let us know if you have more feedback!
