### ISSUE TITLE
Bug: First alias displays 2 '@' symbols

### ISSUE THREAD

**Issue by jmonroynieto** [o02c/obsidian-tab-navigator#22]
It's me again with the nitpicking. In the visual example below, the red underline is the first alias in each tab, and the green one is an example of an additional alias in a note. Only the first one has this issue.

![image1](https://github.com/o02c/obsidian-tab-navigator/assets/10119293/abcd19c1-61a4-437e-a489-9885c573fe30)

**Comment by o02c** [comment]
@jmonroynieto 
Thank you for pointing that out! 😊 We have resolved this issue in version v0.5.2. The first alias now displays correctly in each tab.
