### ISSUE TITLE
Suggestion: add the ability not to hide other Obsidian windows 

### ISSUE THREAD

**Issue by Trebuchosaure** [o02c/obsidian-tab-navigator#24]
Hi, 
thank you very much for your plugin, very useful when too many tabs open ! 

I'm often working with two obsidian windows open on different monitors. But, since this plugin is hiding others tabs, it hides other windows as well, whereas it may be useful to see multiple tabs in the same time.

Do you think it's possible to fix it ? 

Thanks again,

**Comment by o02c** [comment]
Thank you for your feedback! I’m glad to hear that you find the plugin useful.

I understand the issue. I’ll look into this, but it might take some time to find a solution. I appreciate your patience, and I’ll keep you updated on any progress.

**Comment by o02c** [comment]
@Trebuchosaure 
I've implemented support for multi-window in version v0.6.0 (#27). 
Could you please check if this resolves the issue on your end?

**Comment by sql99** [comment]
Thank you! Work Great!

Il giorno dom 15 set 2024 alle ore 10:19 o02c ***@***.***> ha
scritto:
