### ISSUE TITLE
Search tabs work only in current tab not in other obsidian windows

### ISSUE THREAD

**Issue by sql99** [o02c/obsidian-tab-navigator#25]
Search tabs work only in current tab not in other obsidian windows. Version 0.5.2

**Comment by o02c** [comment]
Thanks for reporting this issue. I'm aware of it and are working on a fix in Issue #24, but it's proving to be a bit challenging. Just moment, please.

**Comment by o02c** [comment]
@sql99 
I have resolved this issue in version v0.6.0 (#27)

**Comment by sql99** [comment]
Thank you! Work Great!
