### ISSUE TITLE
Feature Request: Clicking on blank area to close the Prompt

### ISSUE THREAD

**Issue by Moyf** [o02c/obsidian-tab-navigator#5]
This is a great plugin, it even makes me feel like it should be a basic feature of OB ❤️️

And for most pop-up boxes in OB (including the settings interface), clicking on the surrounding blank area can automatically close them. 
Could this plugin's pop-up box also support this behavior?

**Comment by o02c** [comment]
@Moyf 
I made this plugin just for fun, but I'm very happy that it seems to be useful.

The feature is now available in version 0.2.3. 
Please update to this version to use it.

**Comment by Moyf** [comment]
Yay it's definitely useful! Thanks! 在 2024年5月7日，03:32，o02c ***@***.***> 写道：﻿
@Moyf
I made this plugin just for fun, but I'm very happy that it seems to be useful.
The feature is now available in version 0.2.3.
Please update to this version to use it.
